### PR TITLE
Add zsh completion for fdroidcl

### PR DESCRIPTION
**Pull request by lolilolicon**
Not implemented:

* Complete :VersionCode after AppID.
* For `install`, `uninstall` & `upgrade`, check devices.
* For `uninstall` / `upgrade`, pass `-i` / `-u` to `search`.

### CODE REVIEW

**Comment by mvdan** [comment]
> check devices.

What do you mean? The tool already throws an error if it requires a device and none is connected.

Note that it might block for a second or two, as that's how long adb takes to start up from scratch.

**Comment by lolilolicon** [comment]
Chill man, nothing wrong with your code :)
I mean this completion code is not checking devices for those commands, due to the wait/complexity involved. I don't think it too useful either, so didn't bother.

**Comment by mvdan** [comment]
Ah, OK. I'm not worrying, just wondering.

**Comment by lolilolicon** [comment]
Basically, completion for those commands are exactly the same as `show`. I'm too lazy.

**Pull request merged**
